# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=WARN"
    ports:
      traefik:
        expose: false
      web:
        redirectTo: websecure
      websecure:
        asDefault: true
        tls:
          certResolver: letsencrypt
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    certResolvers:
      letsencrypt:
        email: {{ .Values.letsencrypt.email }}
        storage: /data/acme.json
        tlsChallenge: true
    persistence:
      enabled: true
      name: data
      accessMode: ReadWriteOnce
      size: 128Mi
      path: /data
      annotations: {}
